// ── Demo data (used when backend is unreachable) ────────────────────────────
export const DEMO_MANIFESTS = [
  {
    id: "demo-1",
    driveFileId: "demo-1",
    fileName: "family-picnic-2024.jpg",
    mimeType: "image/jpeg",
    thumbnailLink: null,
    webViewLink: null,
    classification: {
      title: "Summer Family Picnic",
      description: "The whole family gathered at Riverside Park for the annual summer picnic. Kids playing on the grass, grandparents watching from the shade.",
      category: "photo",
      people: ["Grandma", "Grandpa", "kids"],
      date_estimate: "2024-07-15",
      tags: ["summer", "picnic", "family", "outdoors"],
      sentiment: "joyful",
    },
    createdAt: "2024-07-16T10:00:00Z",
  },
  {
    id: "demo-2",
    driveFileId: "demo-2",
    fileName: "birthday-card-emma.pdf",
    mimeType: "application/pdf",
    thumbnailLink: null,
    webViewLink: null,
    classification: {
      title: "Emma's Birthday Card",
      description: "A handmade birthday card from Emma with colorful drawings and a sweet message.",
      category: "letter",
      people: ["Emma"],
      date_estimate: "2024-09-22",
      tags: ["birthday", "card", "handmade", "emma"],
      sentiment: "joyful",
    },
    createdAt: "2024-09-23T08:00:00Z",
  },
  {
    id: "demo-3",
    driveFileId: "demo-3",
    fileName: "school-report-fall2024.pdf",
    mimeType: "application/pdf",
    thumbnailLink: null,
    webViewLink: null,
    classification: {
      title: "Fall 2024 School Report",
      description: "Excellent progress report from school showing strong performance in reading and math.",
      category: "document",
      people: ["Emma"],
      date_estimate: "2024-11-15",
      tags: ["school", "report", "grades", "education"],
      sentiment: "neutral",
    },
    createdAt: "2024-11-16T12:00:00Z",
  },
];
